id: 1
sensor: 90
timeout: 0
valve: 1
id: 5
sensor: 63
timeout: 0
valve: 1
id: 6
sensor: 68
timeout: 0
valve: 1
id: 8
sensor: 96
timeout: 0
valve: 1
id: 9
sensor: 76
timeout: 0
valve: 1
id: 10
sensor: 62
timeout: 0
valve: 1
id: 13
sensor: 87
timeout: 0
valve: 1
id: 17
sensor: 100
timeout: 0
valve: 1
id: 18
sensor: 97
timeout: 0
valve: 1
id: 19
sensor: 74
timeout: 0
valve: 1
id: 22
sensor: 64
timeout: 0
valve: 1
id: 26
sensor: 94
timeout: 0
valve: 1
id: 29
sensor: 87
timeout: 0
valve: 1
id: 31
sensor: 62
timeout: 0
valve: 1
id: 37
sensor: 87
timeout: 0
valve: 1
id: 44
sensor: 81
timeout: 0
valve: 1
id: 45
sensor: 78
timeout: 0
valve: 1
id: 49
sensor: 75
timeout: 0
valve: 1
id: 51
sensor: 64
timeout: 0
valve: 1
id: 57
sensor: 88
timeout: 0
valve: 1
id: 59
sensor: 83
timeout: 0
valve: 1
id: 71
sensor: 63
timeout: 0
valve: 1
id: 73
sensor: 96
timeout: 0
valve: 1
id: 74
sensor: 67
timeout: 0
valve: 1
id: 77
sensor: 85
timeout: 0
valve: 1
id: 78
sensor: 62
timeout: 0
valve: 1
id: 79
sensor: 68
timeout: 0
valve: 1
id: 86
sensor: 91
timeout: 0
valve: 1
id: 89
sensor: 93
timeout: 0
valve: 1
id: 96
sensor: 70
timeout: 0
valve: 1
id: 100
sensor: 65
timeout: 0
valve: 1
id: 4
sensor: 91
timeout: 0
valve: 1
id: 11
sensor: 72
timeout: 0
valve: 1
id: 14
sensor: 81
timeout: 0
valve: 1
id: 28
sensor: 65
timeout: 0
valve: 1
id: 30
sensor: 83
timeout: 0
valve: 1
id: 33
sensor: 69
timeout: 0
valve: 1
id: 39
sensor: 87
timeout: 0
valve: 1
id: 40
sensor: 100
timeout: 0
valve: 1
id: 41
sensor: 84
timeout: 0
valve: 1
id: 42
sensor: 62
timeout: 0
valve: 1
id: 48
sensor: 73
timeout: 0
valve: 1
id: 53
sensor: 65
timeout: 0
valve: 1
id: 54
sensor: 83
timeout: 0
valve: 1
id: 55
sensor: 90
timeout: 0
valve: 1
id: 56
sensor: 86
timeout: 0
valve: 1
id: 58
sensor: 93
timeout: 0
valve: 1
id: 62
sensor: 84
timeout: 0
valve: 1
id: 63
sensor: 71
timeout: 0
valve: 1
id: 66
sensor: 85
timeout: 0
valve: 1
id: 68
sensor: 93
timeout: 0
valve: 1
id: 70
sensor: 90
timeout: 0
valve: 1
id: 75
sensor: 70
timeout: 0
valve: 1
id: 81
sensor: 95
timeout: 0
valve: 1
id: 82
sensor: 67
timeout: 0
valve: 1
id: 84
sensor: 92
timeout: 0
valve: 1
id: 88
sensor: 82
timeout: 0
valve: 1
id: 91
sensor: 68
timeout: 0
valve: 1
id: 92
sensor: 91
timeout: 0
valve: 1
id: 97
sensor: 65
timeout: 0
valve: 1
id: 2
sensor: 86
timeout: 0
valve: 1
id: 12
sensor: 86
timeout: 0
valve: 1
id: 25
sensor: 72
timeout: 0
valve: 1
id: 35
sensor: 100
timeout: 0
valve: 1
id: 43
sensor: 68
timeout: 0
valve: 1
id: 46
sensor: 63
timeout: 0
valve: 1
id: 69
sensor: 91
timeout: 0
valve: 1
id: 76
sensor: 83
timeout: 0
valve: 1
id: 83
sensor: 64
timeout: 0
valve: 1
id: 85
sensor: 75
timeout: 0
valve: 1
id: 87
sensor: 98
timeout: 0
valve: 1
id: 90
sensor: 62
timeout: 0
valve: 1
id: 94
sensor: 84
timeout: 0
valve: 1
id: 98
sensor: 80
timeout: 0
valve: 1
id: 7
sensor: 68
timeout: 0
valve: 1
id: 23
sensor: 72
timeout: 0
valve: 1
id: 27
sensor: 81
timeout: 0
valve: 1
id: 34
sensor: 82
timeout: 0
valve: 1
id: 36
sensor: 89
timeout: 0
valve: 1
id: 50
sensor: 62
timeout: 0
valve: 1
id: 61
sensor: 92
timeout: 0
valve: 1
id: 64
sensor: 70
timeout: 0
valve: 1
id: 65
sensor: 68
timeout: 0
valve: 1
id: 67
sensor: 99
timeout: 0
valve: 1
id: 93
sensor: 78
timeout: 0
valve: 1
id: 20
sensor: 91
timeout: 0
valve: 1
id: 24
sensor: 61
timeout: 0
valve: 1
id: 32
sensor: 86
timeout: 0
valve: 1
id: 60
sensor: 69
timeout: 0
valve: 1
id: 72
sensor: 66
timeout: 0
valve: 1
id: 80
sensor: 85
timeout: 0
valve: 1
id: 95
sensor: 70
timeout: 0
valve: 1
id: 99
sensor: 62
timeout: 0
valve: 1
id: 16
sensor: 73
timeout: 0
valve: 1
id: 38
sensor: 79
timeout: 0
valve: 1
id: 47
sensor: 65
timeout: 0
valve: 1
id: 15
sensor: 95
timeout: 0
valve: 1
id: 21
sensor: 74
timeout: 0
valve: 1
id: 52
sensor: 81
timeout: 0
valve: 1
id: 3
sensor: 100
timeout: 0
valve: 1
