authentication:
  password: abc123
  user: pi
db:
  name: ../test/test_db.db
  table:
  - fields: 'id INTEGER PRIMARY KEY AUTOINCREMENT, channel_address TEXT NOT NULL, datetimes TEXT NOT
      NULL, readings FLOAT NOT NULL '
    name: HW_reading
hardware:
  input:
  - callibrate_condition: 30
    channel_address: p1/n1/p1
    hardware: moist sensor
    id: 4
    port: 0
    type: sensor
  - callibrate_condition: 40
    channel_address: p1/n2/p1
    hardware: moist sensor
    id: 5
    port: 7
    type: sensor
  output:
  - channel_address: p1
    hardware: pump
    id: 1
    port: 21
    type: Centrifugal
  - channel_address: p1/n1/p1
    hardware: valve
    id: 2
    port: 21
    type: nozzle
  - channel_address: p1/n2/p1
    hardware: valve
    id: 3
    port: 20
    type: drip
schedule:
  day: '*'
  hour: '*'
  minute: '*/2'
  month: '*'
  week: '*'
  year: '*'
