authentication:
  password: abc123
  user: brandon
db:
  name: ../test/test_db.db
  table:
  - fields: 'id int PRIMARY KEY, channel_address text NOT NULL, datetimes text NOT
      NULL, readings float NOT NULL '
    name: HW_reading
hardware:
  input:
  - callibrate_condition: 50
    channel_address: p1/n1/p1
    hardware: moist sensor
    id: 4
    port: 17
    type: sensor
  - callibrate_condition: 60
    channel_address: p1/n2/p1
    hardware: moist sensor
    id: 5
    port: 15
    type: sensor
  output:
  - channel_address: p1
    hardware: pump
    id: 1
    port: 21
    type: Centrifugal
  - channel_address: p1/n1/p1
    hardware: valve
    id: 2
    port: 20
    type: nozzle
  - channel_address: p1/n2/p1
    hardware: valve
    id: 3
    port: 21
    type: drip
schedule:
  day: '*'
  hour: 0800, 1800
  minute: '*'
  month: '*'
  week: '*'
  year: '*'
